### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by ForrestVV** [kot32go/dynamic-load-view#1]
//Replace the View's mResources and recovery the Activity's avoid disorder of Resources
Reflect.onObject(getContext()).set("mResources", null);
getContext().getResources();

这两行代码的作用是什么？

**Comment by kot32go** [comment]
重置宿主Activity 的Resource，防止宿主的资源和插件的资源混淆

**Comment by ForrestVV** [comment]
@kot32go 可是，从源码上面来看：
Reflect.onObject(getContext()).set("mResources", null); --> 将 ContextImpl的mResources置为 null
getContext().getResources(); --> return mResources

“重置宿主Activity 的Resource，防止宿主的资源和插件的资源混淆”，这个功能是怎么做到的？

**Comment by kot32go** [comment]
@Override
    public Resources getResources() {
        if (mResources != null) {
            return mResources;
        }
        if (mOverrideConfiguration == null) {
            mResources = super.getResources();
            return mResources;
        } else {
            Context resc = createConfigurationContext(mOverrideConfiguration);
            mResources = resc.getResources();
            return mResources;
        }
    }

源码当中：当 mResource 是空的时候，会构造 mResource

**Comment by ForrestVV** [comment]
@kot32go 明白，受教了。
